### ISSUE TITLE
能分享下你做wechat_dll_rs的经验吗？

### ISSUE THREAD

**Issue by 1893945** [RstursOC/wechat_dll_rs#1]
你好，
最近接了一个变态的任务要hook wechat的，现在完全没有头绪，向请教你做这个项目的思路和经验

**Comment by RstursOC** [comment]
基本上是从c++版本教程学来的，首先要去学习汇编基础，只要可以写基础的汇编，比如传递参数，调用函数，跳到自己的函数地址处理后再返回原来的函数等项目需要的功能，啥语言都不是问题。其次是找call 地址，这些网上都有教程，现在用老版本的方法来找新版本的地址可能多了一点东西，但是基本思路是没问题的，利用汇编基础知识，用分析工具一个一个地址找和测试。找到地址后，编写汇编代码调用即可。
过程需要大量实践，最好参考同类的代码不局限于rust，其他人开源的c++项目也可以参考。
